baseURL = "http://joeyang0426.github.io"
languageCode = "zh-tw"
title = "Joe's Blog"
theme = "maupassant-hugo"

[author]
  name = "Joe"

[params]
  author = "Joe Yang"
  subtitle = "HI, MY NAME IS JOE YANG & I AM A Camera, Software Engineer. WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL IMAGE ALGORITM, CAMERA DESIGNER AND DEVELOPER."
  keywords = "BSP, GPU, Android, RTOS, ThreadX, Camera system, Digital Image process"
  description = "專注在影像產品開發"